---
host:
  hostname: node
  count: 3
  cpu: 1
  memory: 1024
ip:
  network: '192.168.3'
  start: 40
  domain: 'test.local'
support_user: support
configs:
  run_as_user: kafka
  install_folder: /opt/kafka
  log_folder: /var/log/kafka
bridge: "enp6s0f0"
software:
  box: bento/ubuntu-24.04
  scala: 2.13
  kafka: 3.9.1
